version: '3.8'

services:
  app:
    build: .
    container_name: scrapper
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
    command: python main.py

  test:
    build: .
    container_name: scrapper-test
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    command: pytest tests/ -v 